version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin1
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  auth_service:
    stdin_open: true
    build:
      context: ./auth
      dockerfile: ./Dockerfile
    container_name: auth_service
    depends_on:
      - postgres
    ports:
      - "4000:4000"
    restart: always
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: auth_service

  flight_service:
    stdin_open: true
    build:
      context: ./flight
      dockerfile: ./Dockerfile
    container_name: flight_service
    depends_on:
      - postgres
    ports:
      - "3002:3002"
    restart: always
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      DB_DATABASE: flight_service


  gateway_service:
    stdin_open: true
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    container_name: gateway_service
    ports:
      - "3000:3000"
    restart: always


volumes:
  postgres-data:
  pgadmin-data:
